### ISSUE TITLE
Linters proposal

### ISSUE THREAD

**Issue by KabbAmine** [zyklus/atom-linter-jade#1]
Hi

Check those new linters: [jadelint](https://github.com/rrdelaney/jadelint) & [jade-lint](https://github.com/benedfit/jade-lint).
I don't know which one is the best, but both of them provide a good set of rule customization.

**Comment by zyklus** [comment]
Thanks, will do :)  I wrote this like a month ago (though just published it yesterday), it's rather funny that _now_ there are two new linters!

**Comment by zyklus** [comment]
precursory testing shows that neither one is ready, though I'll keep an eye on them (they miss very basic things like "else without if" that the actual compiler throws on)

**Comment by zyklus** [comment]
Implemented in v0.2.0 / 2d6e02ca7e222fd4d830b319c0fa0bfc5c876970

**Comment by zyklus** [comment]
And added the other linter as well (they have very different rules at the moment)

**Comment by KabbAmine** [comment]
If will be really great if those linters merge into one project (https://github.com/benedfit/jade-lint/issues/13).
Anyway its good to finally have a jade linter in atom, thanks for your work.
